// import './globals.css'
import './bootstrap.min.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Login System',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={inter.className}
        suppressHydrationWarning={true}
        style={{ height: '100vh', width: '100vw' }}
      >
        {children}
      </body>
    </html>
  );
}
